# -----------------------------------------------------------------------------
# Compiler and Flags
# -----------------------------------------------------------------------------

# C compiler
CC = gcc

# C flags:
# -Wall -Wextra = Show all warnings (good practice)
# -g = Add debugging information
# -std=c11 = Use the C11 standard
# -MMD -MP = Generate dependency files (for header changes)
CFLAGS = -Wall -Wextra -g -std=c11 -MMD -MP

# Include directories (-I tells the compiler where to find .h files)
IDIRS = -Iinc

# Linker flags (if any)
LDFLAGS =

# Libraries (e.g., -lm for math library)
LIBS =

# -----------------------------------------------------------------------------
# Project Structure
# -----------------------------------------------------------------------------

# Name of the final executable
TARGET = my_program

# Directories
SRCDIR = src
OBJDIR = obj
INCDIR = inc

# -----------------------------------------------------------------------------
# Automatic File Discovery
# -----------------------------------------------------------------------------

# Find all .c files in the source directory
# e.g., src/main.c src/utils.c
SOURCES = $(wildcard $(SRCDIR)/*.c)

# Create a list of object files in the obj directory
# e.g., obj/main.o obj/utils.o
OBJECTS = $(patsubst $(SRCDIR)/%.c, $(OBJDIR)/%.o, $(SOURCES))

# Create a list of dependency files (generated by -MMD)
# e.g., obj/main.d obj/utils.d
DEPS = $(OBJECTS:.o=.d)

# -----------------------------------------------------------------------------
# Main Rules
# -----------------------------------------------------------------------------

# Default rule: build everything
.PHONY: all
all: $(TARGET)

# Rule to link the final executable
# Depends on all object files
$(TARGET): $(OBJECTS)
	@echo "Linking executable..."
	$(CC) $(OBJECTS) -o $(TARGET) $(LDFLAGS) $(LIBS)
	@echo "Build complete: $(TARGET)"

# Rule to compile a .c file into a .o file
# e.g., turns src/main.c into obj/main.o
$(OBJDIR)/%.o: $(SRCDIR)/%.c
	@mkdir -p $(@D) # Create the obj directory if it doesn't exist
	@echo "Compiling $<..."
	$(CC) $(CFLAGS) $(IDIRS) -c $< -o $@

# Rule to run the program
.PHONY: run
run: $(TARGET)
	@echo "Running $(TARGET)..."
	./$(TARGET)

# Rule to clean up build files
.PHONY: clean
clean:
	@echo "Cleaning up build files..."
	rm -f $(TARGET)
	rm -rf $(OBJDIR) # Remove the entire obj directory

# -----------------------------------------------------------------------------
# Include Dependencies
# -----------------------------------------------------------------------------

# Include the .d files generated by the compiler.
# The '-' ignores errors if the file doesn't exist (e.g., on first build).
-include $(DEPS)
